name: Graphene tests

on: [push]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        llvm-version: [15, 16]
        runner: [ubuntu-latest, buildjet-2vcpu-ubuntu-2204-arm]

    runs-on: ${{ matrix.runner }}

    env:
      GRAPHENE_CLANG_CMD: clang-${{ matrix.llvm-version }}
      GRAPHENE_LLI_CMD: lli-${{ matrix.llvm-version }}

    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.11
      run: sudo apt-get install -y python3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install clang and lli
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{ matrix.llvm-version }}
        sudo apt-get install -y llvm-${{ matrix.llvm-version }}-runtime
    - name: Run tests
      run: python tests/run_tests.py
