name: Graphene tests

on: [push]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        llvm-version: [17, 18]
        python-version: [3.12, 3.13]
        runner: [ubuntu-latest, buildjet-2vcpu-ubuntu-2204-arm]

    runs-on: ${{ matrix.runner }}

    env:
      GRAPHENE_CLANG_CMD: clang-${{ matrix.llvm-version }}
      GRAPHENE_LLC_CMD: llc-${{ matrix.llvm-version }}
      GRAPHENE_LLD_CMD: ld.lld-${{ matrix.llvm-version }}
      GRAPHENE_LLI_CMD: lli-${{ matrix.llvm-version }}
      GRAPHENE_LLVM_AR_CMD: llvm-ar-${{ matrix.llvm-version }}
      GRAPHENE_LLVM_MC_CMD: llvm-mc-${{ matrix.llvm-version }}
      GRAPHENE_OPT_CMD: opt-${{ matrix.llvm-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        show-progress: false
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install hatch
      run: pip install hatch==1.9.4
    - name: Install clang and lli
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{ matrix.llvm-version }}
        sudo apt-get install -y llvm-${{ matrix.llvm-version }}-runtime
    - name: Fetch tags
      run: git fetch --tags --force origin
    - name: Run tests
      run: hatch run dev:test
