name: Graphene tests

on: [push]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        llvm-version: [16, 17]
        runner: [ubuntu-latest, buildjet-2vcpu-ubuntu-2204-arm]

    runs-on: ${{ matrix.runner }}

    env:
      GRAPHENE_CLANG_CMD: clang-${{ matrix.llvm-version }}
      GRAPHENE_LLI_CMD: lli-${{ matrix.llvm-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        show-progress: false
    - name: Install Python 3.11
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.11 python3.11-venv
        python3.11 -m venv venv/bin/activate
    - name: Install hatch
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatch
    - name: Install clang and lli
      run: |
        # XXX workaround for https://github.com/llvm/llvm-project/issues/64182
        sudo apt-get purge --auto-remove llvm python3-lldb-14 llvm-14
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{ matrix.llvm-version }}
        sudo apt-get install -y llvm-${{ matrix.llvm-version }}-runtime
    - name: Fetch tags
      run: git fetch --tags --force origin
    - name: Run tests
      run: hatch run test:run
