name: Graphene tests

on: [push]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        llvm-version: [15, 16]
        runner: [ubuntu-latest, buildjet-2vcpu-ubuntu-2204-arm]

    runs-on: ${{ matrix.runner }}

    env:
      GRAPHENE_CLANG_CMD: clang-${{ matrix.llvm-version }}
      GRAPHENE_LLI_CMD: lli-${{ matrix.llvm-version }}
      PYTHON_CMD: python3.11

    steps:
    - uses: actions/checkout@v3
    - name: Install Python
      run: sudo apt-get install -y $PYTHON_CMD
    - name: Install dependencies
      run: |
        $PYTHON_CMD -m pip install --upgrade pip
        $PYTHON_CMD -m pip install -r requirements.txt
    - name: Install clang and lli
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{ matrix.llvm-version }}
        sudo apt-get install -y llvm-${{ matrix.llvm-version }}-runtime
    - name: Run tests
      run: $PYTHON_CMD tests/run_tests.py
