name: Graphene tests

on: [push]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        llvm-version: [16, 17]
        runner: [ubuntu-latest, buildjet-2vcpu-ubuntu-2204-arm]

    runs-on: ${{ matrix.runner }}

    env:
      GRAPHENE_CLANG_CMD: clang-${{ matrix.llvm-version }}
      GRAPHENE_LLI_CMD: lli-${{ matrix.llvm-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        show-progress: false
    - name: Install pipx
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
    - name: Install hatch
      run: pipx install hatch
    - name: Install Python
      run: hatch python install 3.12
    - name: Install clang and lli
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{ matrix.llvm-version }}
        sudo apt-get install -y llvm-${{ matrix.llvm-version }}-runtime
    - name: Fetch tags
      run: git fetch --tags --force origin
    - name: Run tests
      run: hatch run dev:test
